repos:
  - repo: local
    hooks:
      - id: ruff-format
        language: python
        name: ruff-format
        pass_filenames: false
        language_version: python3.8
        entry: poetry run ruff format social_media_downloader

  - repo: local
    hooks:
      - id: ruff
        language: python
        name: ruff
        pass_filenames: false
        language_version: python3.8
        entry: poetry run ruff check --fix --exit-non-zero-on-fix --show-fixes social_media_downloader

  - repo: local
    hooks:
      - id: mypy
        language: python
        name: mypy
        pass_filenames: false
        entry: poetry run mypy social_media_downloader --show-error-codes
